name: Continuous Integration

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'
          cache-dependency-path: backend/go.sum

      - name: Install Dependencies
        working-directory: backend
        run: go get .

      - name: Run Tests
        working-directory: backend
        run: go test

